### ISSUE TITLE
value is "\" can not copy to mysql

### ISSUE THREAD

**Issue by ywyt738** [duckdb/duckdb_mysql#58]
### What happens?

If my field's value is \ , it can not be imported to mysql with COPY command.
Because the import sql is
```sql
INSERT table value ('\')
```
The sql will report syntax error.

### To Reproduce

1. create a table in duckdb, insert a row with field's value is \
2. create the new table in mysql, use 
```sql
create table table_name as from db.table
```

### OS:

linux & mac

### DuckDB Version:

0.10.1

### DuckDB Client:

cli

### Full Name:

Xiaojun Huang

### Affiliation:

MHP

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have not tested with any build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
@ywyt738 thanks! I transferred the issue to the `duckdb_mysql` repository. We'll take a look.

**Comment by danilobellini** [comment]
Past week I suffered from a data integrity issue where strings like `12345\0123` had the `\0` replaced by the null character and strings like `R\L` lost the backslash while copying data from a CSV to MySQL through DuckDB. I have only noticed it because of a trailing backslash in one of these input strings, which broke the process the same way described in this issue.
